const data=window.__AURI_BROWSER_OVERLAY__||{mode:"menu"};const root=document.querySelector("#overlay-root");
const esc=(v)=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const emit=(action,detail={})=>window.__TAURI__?.event?.emit?.("auri-browser-overlay-action",{action,...detail});
const item=(icon,label,action)=>`<button class="menu-item" type="button" data-action="${action}"><span class="icon">${icon}</span><strong>${label}</strong></button>`;
const head=(icon,eyebrow,title)=>`<header class="dialog-header"><div class="dialog-title"><span class="dialog-icon">${icon}</span><div><small>${eyebrow}</small><h1>${title}</h1></div></div><button class="close-button" type="button" data-action="web-dialog-close" aria-label="Close">×</button></header>`;
const empty=(icon,title,copy)=>`<div class="empty"><span class="list-icon">${icon}</span><strong>${title}</strong><p>${copy}</p></div>`;
function menu(){return `<section class="surface menu" aria-label="Browser menu">${item("＋","New Webview tab","subtab-new").replace('data-action="subtab-new"','data-action="subtab-new" data-type="webview"')}<div class="separator"></div>${item("↻","Reload","web-reload")}${item("←","Back","web-back")}${item("→","Forward","web-forward")}<div class="separator"></div>${item("↗","Open externally","web-external")}${item("↓","Download page","web-download")}${item("☆","Add bookmark","web-add-bookmark")}${item("★","Bookmarks","web-bookmarks")}${item("◷","History","web-history")}<div class="separator"></div><div class="zoom-row"><span>Zoom</span><div class="zoom-controls"><button type="button" data-action="web-zoom-out">−</button><button class="zoom-value" type="button" data-action="web-zoom-reset">${esc(data.zoom||"100%")}</button><button type="button" data-action="web-zoom-in">＋</button></div></div><div class="separator"></div>${item("⌘","Developer tools","web-devtools")}</section>`}
function newTab(){const tabs=[["terminal","⌘","Terminal"],["webview","◎","Webview"],["viewer","◈","Viewer"],["clipboard","▣","Clipboard"],["audio","♪","Audio recording"],["video","▷","Video recording"],["settings","⚙","Settings"],["system","◬","System"],["disk","▤","Disk"],["net","⇄","Network"],["info","ⓘ","Info"]];return `<section class="surface menu" aria-label="New tab menu">${tabs.map(([type,icon,label])=>`<button class="menu-item" type="button" data-action="subtab-new" data-type="${type}"><span class="icon">${icon}</span><strong>${label}</strong></button>`).join("")}</section>`}
function subtabActions(){const id=esc(data.id||"");const move=data.standalone?["↙","Go back to main window","subtab-action-main"]:["↗","Open in new window","subtab-action-window"];return `<section class="surface menu" aria-label="${esc(data.title||"Tab")} actions">${item("↻","Reload tab","subtab-action-reload").replace("data-action=\"subtab-action-reload\"",`data-action="subtab-action-reload" data-id="${id}"`)}${item(move[0],move[1],move[2]).replace(`data-action="${move[2]}"`,`data-action="${move[2]}" data-id="${id}"`)}<div class="separator"></div><button class="menu-item danger" type="button" data-action="subtab-action-close" data-id="${id}"><span class="icon">×</span><strong>Close tab</strong></button></section>`}
function commandMenu(){const icons={terminal:"⌘",webview:"◎",viewer:"◈",clipboard:"▣",audio:"♪",video:"▷",settings:"⚙",system:"◬",disk:"▤",net:"⇄",info:"ⓘ"};const tabs=Array.isArray(data.tabs)?data.tabs:[];return `<section class="surface menu" aria-label="Open tabs and app commands">${tabs.map((tab)=>`<button class="menu-item ${tab.id===data.activeId?"is-active":""}" type="button" data-action="command-menu-tab" data-id="${esc(tab.id)}"><span class="icon">${icons[tab.type]||"·"}</span><strong>${esc(tab.title||"Tab")}</strong></button>`).join("")}<div class="separator"></div><button class="menu-item danger" type="button" data-action="app-exit"><span class="icon">×</span><strong>Exit Auri</strong></button></section>`}
function addBookmark(){const draft=data.bookmarkDraft||{};return `<section class="surface dialog" aria-label="Add bookmark">${head("☆","PAGE","Add bookmark")}<form class="bookmark-form" id="overlay-bookmark-form"><label>Name<input name="name" value="${esc(draft.name||"")}" required autocomplete="off"></label><label>URL<input name="url" type="url" value="${esc(draft.url||"")}" required autocomplete="off" autocapitalize="off" spellcheck="false"></label><div class="form-actions"><button class="action secondary" type="button" data-action="web-dialog-close">Cancel</button><button class="action primary" type="submit">Save bookmark</button></div></form></section>`}
function bookmarks(){const list=Array.isArray(data.bookmarks)?data.bookmarks:[];const rows=list.length?list.map((x)=>`<article class="list-row"><button class="list-open" type="button" data-action="web-bookmark-open" data-url="${esc(x.url)}"><span class="list-icon">★</span><span class="list-copy"><strong>${esc(x.name)}</strong><small>${esc(x.url)}</small></span></button><button class="remove" type="button" data-action="web-bookmark-remove" data-id="${esc(x.id)}">×</button></article>`).join(""):empty("☆","No bookmarks yet","Save the current page from the browser menu.");return `<section class="surface dialog" aria-label="Bookmarks">${head("★","LIBRARY","Bookmarks")}<div class="list">${rows}</div><footer class="dialog-footer"><button class="action primary" type="button" data-action="web-add-bookmark">＋ Add bookmark</button></footer></section>`}
function history(){const list=Array.isArray(data.history)?data.history:[];const rows=list.length?list.map((x)=>`<button class="history-row" type="button" data-action="web-history-open" data-url="${esc(x.url)}"><span class="list-icon">◷</span><span class="list-copy"><strong>${esc(x.title||x.url)}</strong><small>${esc(x.url)}</small></span><time>${esc(new Date(x.at).toLocaleString())}</time></button>`).join(""):empty("◷","No browsing history","Pages opened in Auri will appear here.");return `<section class="surface dialog" aria-label="History">${head("◷","RECENT","History")}<div class="list">${rows}</div><footer class="dialog-footer">${list.length?'<button class="action secondary" type="button" data-action="web-history-clear">Clear history</button>':""}</footer></section>`}
function magic(){return `<section class="surface menu" aria-label="Magic actions">${item("→","Go to URL","web-magic-go")}${item("✦","Ask AI","web-magic-ask")}<div class="separator"></div><p class="hint">Hold ✦ to talk with the live AI</p></section>`}
function toast(){return `<section class="toast-note ${esc(data.level||"info")}" role="status">${esc(data.message||"")}</section>`}
function aiReply(){
  const reply=data.reply||{};
  const segments=Array.isArray(reply.segments)?reply.segments:[];
  const actionRow=(segment)=>{const value=esc(segment.text);const command=segment.kind==="command";return `<div class="ai-action"><pre>${value}</pre><div class="ai-action-buttons"><button type="button" data-action="copy-text" data-value="${value}">Copy</button><button type="button" data-action="assistant-insert" data-value="${value}">Insert</button>${command?`<button class="primary" type="button" data-action="assistant-run" data-value="${value}">Run</button>`:""}</div></div>`};
  const body=reply.status==="loading"||reply.status==="listening"
    ?`<div class="ai-loading">${reply.status==="listening"?"Listening…":"Thinking…"}</div>`
    :reply.status==="streaming"
      ?`<div class="ai-text">${esc(reply.plainText||"")}</div><div class="ai-loading">Responding…</div>`
      :reply.status==="error"
        ?`<div class="ai-text is-error">${esc(reply.plainText||"")}</div>`
        :(segments.map((segment)=>segment.kind==="text"
            ?(segment.text.trim()?`<div class="ai-text">${esc(segment.text.trim())}</div>`:"")
            :actionRow(segment)).join("")||`<div class="ai-text"></div>`);
  return `<section class="surface dialog ai-reply" aria-label="AI reply"><header class="dialog-header"><div class="dialog-title"><span class="dialog-icon">✦</span><div><small>AI REPLY</small><h1>${esc(reply.modelName||"AI")}</h1></div></div><div class="ai-head-actions">${reply.status==="ready"?'<button class="action secondary" type="button" data-action="web-ai-copy">Copy all</button>':""}<button class="close-button" type="button" data-action="web-ai-close" aria-label="Close">×</button></div></header><p class="ai-prompt">${esc(String(reply.prompt||"").slice(0,220))}</p><div class="ai-body">${body}</div>${reply.hasAudio?'<p class="hint">Audio reply is playing in Auri.</p>':""}</section>`;
}
root.innerHTML=data.mode==="new-tab"?newTab():data.mode==="subtab-actions"?subtabActions():data.mode==="command-menu"?commandMenu():data.mode==="magic"?magic():data.mode==="ai-reply"?aiReply():data.mode==="add-bookmark"?addBookmark():data.mode==="bookmarks"?bookmarks():data.mode==="history"?history():data.mode==="toast"?toast():menu();
window.__AURI_UPDATE_ZOOM__=(value)=>{data.zoom=value;const target=document.querySelector(".zoom-value");if(target)target.textContent=value};
root.addEventListener("click",(event)=>{const target=event.target.closest("[data-action]");if(target)emit(target.dataset.action,{id:target.dataset.id||null,url:target.dataset.url||null,type:target.dataset.type||null,value:target.dataset.value||null})});
root.addEventListener("submit",(event)=>{if(event.target.id!=="overlay-bookmark-form")return;event.preventDefault();const values=Object.fromEntries(new FormData(event.target).entries());emit("web-bookmark-save",{name:values.name,url:values.url})});
if(data.mode==="add-bookmark")requestAnimationFrame(()=>{const input=document.querySelector('input[name="name"]');input?.focus();input?.select()});
